# Home route
http://localhost:5000/

###

# Fetch Categories route
http://localhost:5000/categories

###

# Fetch Questions route
http://localhost:5000/questions?page=2

###

# Delete Question route
DELETE http://localhost:5000/questions/25

###

# Add Question route
POST http://localhost:5000/questions
Content-Type: application/json

{
    "answer": "Engine",
    "question": "What is that?",
    "difficulty": 1,
    "category": 4
}

###

# Fetch questions by category route
http://localhost:5000/categories/1/questions

###

# Search questions 
POST http://localhost:5000/questions/search
Content-Type: application/json

{
    "searchTerm": "title"
}

###

# Fetch quiz questions 
POST http://localhost:5000/quizzes
Content-Type: application/json

{
    "previous_questions": [16,17,18],
    "quiz_category": { 
        "id": 2,
        "type": "Science"
    }
}