# Home route
http://localhost:5000/

###

# Fetch Categories route
http://localhost:5000/categories

###

# Fetch Questions route
http://localhost:5000/questions?page=3

###

# Delete Question route
DELETE http://localhost:5000/questions/24

###

# Add Question route
POST http://localhost:5000/questions
Content-Type: application/json

{
    "answer": "Engine",
    "question": "What is that?",
    "difficulty": 1,
    "category": 4
}